import { css, customElement, html, LitElement, property, unsafeCSS } from 'lit-element';
import {style} from './textfield.style'; // Generated by sass preprocessor. See rollup.config.js

@customElement('mdc-text-field')
export class TextField extends LitElement {
  @property()
  label = '';

  @property()
  value = '';

  static get styles() {
    return [css`${unsafeCSS(style)}`];
  }

  render() {
    return html`
    <div class="mdc-text-field">
      <input type="text" id="my-text-field" class="mdc-text-field__input" value=${this.value}>
      <label class="mdc-floating-label" for="my-text-field">${this.label}</label>
      <div class="mdc-line-ripple"></div>
    </div>`;
  }
}
