import { css, customElement, html, LitElement, property, unsafeCSS } from 'lit-element';
import {style} from './button.style'; // Generated by sass preprocessor. See rollup.config.js

@customElement('mdc-button')
export class Button extends LitElement {
  @property()
  icon = '';

  static get styles() {
    return [css`${unsafeCSS(style)}`];
  }

  render() {
    return html`
      <button class="mdc-button">
        <span class="mdc-button__label"><slot></slot></span>
      </button>`;
  }
}
